version: "3.8"

name: safetycrm

services:
  dev-database:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env.development

  redis:
    container_name: safetycrm-dev-redis
    image: redis:7.2
    ports:
      - 6379:6379
